export enum ProposalStatusEnum {
  DRAFT = 'DRAFT',
  COMPLETE = 'COMPLETE',
  SENT = 'SENT',
  COMFIRMED = 'CONFIRMED',
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
  FIXREQUESTED = 'FIXREQUESTED',
}
