name: CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: dcloser-core

jobs:
  push_to_ecr:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DCLOSER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DCLOSER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: aws cli
        run: aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 728796463735.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build and tag Docker image
        run: docker build -f Dockerfile -t 728796463735.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_REPOSITORY:${GITHUB_SHA::7} -t 728796463735.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_REPOSITORY:latest .

      - name: Push Docker image to Amazon ECR
        run: docker push -a 728796463735.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_REPOSITORY
